/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BgOptionsRouteImport } from './routes/bg-options'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWritingSamplesRouteImport } from './routes/dashboard.writing-samples'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BgOptionsRoute = BgOptionsRouteImport.update({
  id: '/bg-options',
  path: '/bg-options',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWritingSamplesRoute = DashboardWritingSamplesRouteImport.update({
  id: '/writing-samples',
  path: '/writing-samples',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bg-options': typeof BgOptionsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/writing-samples': typeof DashboardWritingSamplesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bg-options': typeof BgOptionsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/writing-samples': typeof DashboardWritingSamplesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bg-options': typeof BgOptionsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/writing-samples': typeof DashboardWritingSamplesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bg-options' | '/dashboard' | '/dashboard/writing-samples'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bg-options' | '/dashboard' | '/dashboard/writing-samples'
  id:
    | '__root__'
    | '/'
    | '/bg-options'
    | '/dashboard'
    | '/dashboard/writing-samples'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BgOptionsRoute: typeof BgOptionsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bg-options': {
      id: '/bg-options'
      path: '/bg-options'
      fullPath: '/bg-options'
      preLoaderRoute: typeof BgOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/writing-samples': {
      id: '/dashboard/writing-samples'
      path: '/writing-samples'
      fullPath: '/dashboard/writing-samples'
      preLoaderRoute: typeof DashboardWritingSamplesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardWritingSamplesRoute: typeof DashboardWritingSamplesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardWritingSamplesRoute: DashboardWritingSamplesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BgOptionsRoute: BgOptionsRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
