/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingSamplesRouteImport } from './routes/writing-samples'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BgOptionsRouteImport } from './routes/bg-options'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingSamplesQuestionIdRouteImport } from './routes/writing-samples.$questionId'

const WritingSamplesRoute = WritingSamplesRouteImport.update({
  id: '/writing-samples',
  path: '/writing-samples',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BgOptionsRoute = BgOptionsRouteImport.update({
  id: '/bg-options',
  path: '/bg-options',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSamplesQuestionIdRoute =
  WritingSamplesQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => WritingSamplesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bg-options': typeof BgOptionsRoute
  '/dashboard': typeof DashboardRoute
  '/writing-samples': typeof WritingSamplesRouteWithChildren
  '/writing-samples/$questionId': typeof WritingSamplesQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bg-options': typeof BgOptionsRoute
  '/dashboard': typeof DashboardRoute
  '/writing-samples': typeof WritingSamplesRouteWithChildren
  '/writing-samples/$questionId': typeof WritingSamplesQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bg-options': typeof BgOptionsRoute
  '/dashboard': typeof DashboardRoute
  '/writing-samples': typeof WritingSamplesRouteWithChildren
  '/writing-samples/$questionId': typeof WritingSamplesQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bg-options'
    | '/dashboard'
    | '/writing-samples'
    | '/writing-samples/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bg-options'
    | '/dashboard'
    | '/writing-samples'
    | '/writing-samples/$questionId'
  id:
    | '__root__'
    | '/'
    | '/bg-options'
    | '/dashboard'
    | '/writing-samples'
    | '/writing-samples/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BgOptionsRoute: typeof BgOptionsRoute
  DashboardRoute: typeof DashboardRoute
  WritingSamplesRoute: typeof WritingSamplesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing-samples': {
      id: '/writing-samples'
      path: '/writing-samples'
      fullPath: '/writing-samples'
      preLoaderRoute: typeof WritingSamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bg-options': {
      id: '/bg-options'
      path: '/bg-options'
      fullPath: '/bg-options'
      preLoaderRoute: typeof BgOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing-samples/$questionId': {
      id: '/writing-samples/$questionId'
      path: '/$questionId'
      fullPath: '/writing-samples/$questionId'
      preLoaderRoute: typeof WritingSamplesQuestionIdRouteImport
      parentRoute: typeof WritingSamplesRoute
    }
  }
}

interface WritingSamplesRouteChildren {
  WritingSamplesQuestionIdRoute: typeof WritingSamplesQuestionIdRoute
}

const WritingSamplesRouteChildren: WritingSamplesRouteChildren = {
  WritingSamplesQuestionIdRoute: WritingSamplesQuestionIdRoute,
}

const WritingSamplesRouteWithChildren = WritingSamplesRoute._addFileChildren(
  WritingSamplesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BgOptionsRoute: BgOptionsRoute,
  DashboardRoute: DashboardRoute,
  WritingSamplesRoute: WritingSamplesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
