/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BgOptionsRouteImport } from './routes/bg-options'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingSamplesIndexRouteImport } from './routes/writing-samples.index'
import { Route as SpeakingSamplesIndexRouteImport } from './routes/speaking-samples.index'
import { Route as WritingSamplesQuestionIdRouteImport } from './routes/writing-samples.$questionId'
import { Route as SpeakingSamplesCategoryTopicRouteImport } from './routes/speaking-samples.$category.$topic'
import { Route as SpeakingSamplesCategoryTopicFollowupIndexRouteImport } from './routes/speaking-samples.$category.$topic.followup.$index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BgOptionsRoute = BgOptionsRouteImport.update({
  id: '/bg-options',
  path: '/bg-options',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSamplesIndexRoute = WritingSamplesIndexRouteImport.update({
  id: '/writing-samples/',
  path: '/writing-samples/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingSamplesIndexRoute = SpeakingSamplesIndexRouteImport.update({
  id: '/speaking-samples/',
  path: '/speaking-samples/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSamplesQuestionIdRoute =
  WritingSamplesQuestionIdRouteImport.update({
    id: '/writing-samples/$questionId',
    path: '/writing-samples/$questionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpeakingSamplesCategoryTopicRoute =
  SpeakingSamplesCategoryTopicRouteImport.update({
    id: '/speaking-samples/$category/$topic',
    path: '/speaking-samples/$category/$topic',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpeakingSamplesCategoryTopicFollowupIndexRoute =
  SpeakingSamplesCategoryTopicFollowupIndexRouteImport.update({
    id: '/followup/$index',
    path: '/followup/$index',
    getParentRoute: () => SpeakingSamplesCategoryTopicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bg-options': typeof BgOptionsRoute
  '/dashboard': typeof DashboardRoute
  '/writing-samples/$questionId': typeof WritingSamplesQuestionIdRoute
  '/speaking-samples/': typeof SpeakingSamplesIndexRoute
  '/writing-samples/': typeof WritingSamplesIndexRoute
  '/speaking-samples/$category/$topic': typeof SpeakingSamplesCategoryTopicRouteWithChildren
  '/speaking-samples/$category/$topic/followup/$index': typeof SpeakingSamplesCategoryTopicFollowupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bg-options': typeof BgOptionsRoute
  '/dashboard': typeof DashboardRoute
  '/writing-samples/$questionId': typeof WritingSamplesQuestionIdRoute
  '/speaking-samples': typeof SpeakingSamplesIndexRoute
  '/writing-samples': typeof WritingSamplesIndexRoute
  '/speaking-samples/$category/$topic': typeof SpeakingSamplesCategoryTopicRouteWithChildren
  '/speaking-samples/$category/$topic/followup/$index': typeof SpeakingSamplesCategoryTopicFollowupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bg-options': typeof BgOptionsRoute
  '/dashboard': typeof DashboardRoute
  '/writing-samples/$questionId': typeof WritingSamplesQuestionIdRoute
  '/speaking-samples/': typeof SpeakingSamplesIndexRoute
  '/writing-samples/': typeof WritingSamplesIndexRoute
  '/speaking-samples/$category/$topic': typeof SpeakingSamplesCategoryTopicRouteWithChildren
  '/speaking-samples/$category/$topic/followup/$index': typeof SpeakingSamplesCategoryTopicFollowupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bg-options'
    | '/dashboard'
    | '/writing-samples/$questionId'
    | '/speaking-samples/'
    | '/writing-samples/'
    | '/speaking-samples/$category/$topic'
    | '/speaking-samples/$category/$topic/followup/$index'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bg-options'
    | '/dashboard'
    | '/writing-samples/$questionId'
    | '/speaking-samples'
    | '/writing-samples'
    | '/speaking-samples/$category/$topic'
    | '/speaking-samples/$category/$topic/followup/$index'
  id:
    | '__root__'
    | '/'
    | '/bg-options'
    | '/dashboard'
    | '/writing-samples/$questionId'
    | '/speaking-samples/'
    | '/writing-samples/'
    | '/speaking-samples/$category/$topic'
    | '/speaking-samples/$category/$topic/followup/$index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BgOptionsRoute: typeof BgOptionsRoute
  DashboardRoute: typeof DashboardRoute
  WritingSamplesQuestionIdRoute: typeof WritingSamplesQuestionIdRoute
  SpeakingSamplesIndexRoute: typeof SpeakingSamplesIndexRoute
  WritingSamplesIndexRoute: typeof WritingSamplesIndexRoute
  SpeakingSamplesCategoryTopicRoute: typeof SpeakingSamplesCategoryTopicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bg-options': {
      id: '/bg-options'
      path: '/bg-options'
      fullPath: '/bg-options'
      preLoaderRoute: typeof BgOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing-samples/': {
      id: '/writing-samples/'
      path: '/writing-samples'
      fullPath: '/writing-samples/'
      preLoaderRoute: typeof WritingSamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking-samples/': {
      id: '/speaking-samples/'
      path: '/speaking-samples'
      fullPath: '/speaking-samples/'
      preLoaderRoute: typeof SpeakingSamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing-samples/$questionId': {
      id: '/writing-samples/$questionId'
      path: '/writing-samples/$questionId'
      fullPath: '/writing-samples/$questionId'
      preLoaderRoute: typeof WritingSamplesQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking-samples/$category/$topic': {
      id: '/speaking-samples/$category/$topic'
      path: '/speaking-samples/$category/$topic'
      fullPath: '/speaking-samples/$category/$topic'
      preLoaderRoute: typeof SpeakingSamplesCategoryTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking-samples/$category/$topic/followup/$index': {
      id: '/speaking-samples/$category/$topic/followup/$index'
      path: '/followup/$index'
      fullPath: '/speaking-samples/$category/$topic/followup/$index'
      preLoaderRoute: typeof SpeakingSamplesCategoryTopicFollowupIndexRouteImport
      parentRoute: typeof SpeakingSamplesCategoryTopicRoute
    }
  }
}

interface SpeakingSamplesCategoryTopicRouteChildren {
  SpeakingSamplesCategoryTopicFollowupIndexRoute: typeof SpeakingSamplesCategoryTopicFollowupIndexRoute
}

const SpeakingSamplesCategoryTopicRouteChildren: SpeakingSamplesCategoryTopicRouteChildren =
  {
    SpeakingSamplesCategoryTopicFollowupIndexRoute:
      SpeakingSamplesCategoryTopicFollowupIndexRoute,
  }

const SpeakingSamplesCategoryTopicRouteWithChildren =
  SpeakingSamplesCategoryTopicRoute._addFileChildren(
    SpeakingSamplesCategoryTopicRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BgOptionsRoute: BgOptionsRoute,
  DashboardRoute: DashboardRoute,
  WritingSamplesQuestionIdRoute: WritingSamplesQuestionIdRoute,
  SpeakingSamplesIndexRoute: SpeakingSamplesIndexRoute,
  WritingSamplesIndexRoute: WritingSamplesIndexRoute,
  SpeakingSamplesCategoryTopicRoute:
    SpeakingSamplesCategoryTopicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
